# ------------------------------------------------------------
# Conda Environment Configuration for Cyberbullying MLOps
# ------------------------------------------------------------
name: cyberbullying-mlops
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - sqlite
  - curl
  - pip:
      - flask==3.0.3
      - mlflow==2.14.2
      - requests==2.32.3
      - gunicorn==22.0.0
      - nltk==3.9.1
      - tqdm
      - joblib
      - markupsafe==2.1.5
      - -r C:/deploy_model/requirements.txt.txt